steps:
# We use this instead of the one from GNU FTP for dynamic module support.
# TODO: Explain that parameters.version is not support for Windows install.
- script: |
    set MSYS_PATH=%CD%\ci-tools\msys2
    choco install msys2 --params="/InstallDir:%MSYS_PATH% /NoPath"
    set PATH=%MSYS_PATH%\usr\bin;%PATH%
    pacman -S --noconfirm --needed mingw-w64-x86_64-emacs
    echo ##vso[task.prependpath]%MSYS_PATH%\mingw64\bin
  displayName: Install Emacs (Windows)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
    set -e
    sudo apt-get install ruby libgtk-3-dev libxpm-dev libgnutls-dev
  displayName: Install Emacs's pre-requisites (Linux)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

# XXX: Please don't use homebrew!
- bash: |
    set -e
    brew install pkg-config gnutls libxml2
    # https://github.com/remacs/remacs/issues/155 (pkg-config)
    brew outdated pkg-config || brew upgrade pkg-config
    # https://github.com/remacs/remacs/issues/886 (libxml2, macOS 10.14)
    echo "##vso[task.setvariable variable=PKG_CONFIG_PATH]/usr/local/opt/libxml2/lib/pkgconfig"
  displayName: Install Emacs's pre-requisites (macOS)
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Darwin'))

- bash: |
    set -e
    export PATH="$HOME/.evm/bin:$PATH"
    git clone -b max-26.2 https://github.com/ubolonton/evm.git $HOME/.evm
    evm config path /tmp
    evm install $EVM_EMACS --use --skip
    echo "##vso[task.setvariable variable=PATH]$PATH"
  displayName: Install Emacs $(EVM_EMACS)
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))
