parameters:
  version: "8.0.0"

# TODO: Install and get llvm location in a less fragile way.
steps:
- script: |
    choco install llvm --version ${{ parameters.version }}
    echo "##vso[task.setvariable variable=LIBCLANG_PATH]%SystemDrive%\Program Files\LLVM\bin"
  displayName: Install LLVM ${{ parameters.version }} and set up LIBCLANG_PATH
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))
