steps:
- powershell: |
    $bundle_version = ((cask eval "(progn (require 'tree-sitter-langs-build) (princ tree-sitter-langs--version))") | Out-String).Trim()
    echo "##vso[task.setvariable variable=BUNDLE_VERSION]$bundle_version"
    cask eval "(progn (require 'tree-sitter-langs-build) (tree-sitter-langs-create-bundle))"
    ls
    cask package
  displayName: Create grammar bundle (Windows)
  workingDirectory: langs
  condition: and(succeeded(), eq(variables['Agent.OS'], 'Windows_NT'))

- bash: |
    set -e
    BUNDLE_VERSION=$(cask eval "(progn (require 'tree-sitter-langs-build) (princ tree-sitter-langs--version))")
    echo "##vso[task.setvariable variable=BUNDLE_VERSION]$BUNDLE_VERSION"
    cask eval "(progn (require 'tree-sitter-langs-build) (tree-sitter-langs-create-bundle))"
    ls
    cask package
  displayName: Create grammar bundle
  workingDirectory: langs
  condition: and(succeeded(), ne(variables['Agent.OS'], 'Windows_NT'))
