[package]
name = "emacs-tree-sitter"
version = "0.13.1"
authors = ["Tuấn-Anh Nguyễn <ubolonton@gmail.com>"]
edition = "2018"
publish = false

[lib]
path = "src/lib.rs"
name = "tsc_dyn"
crate-type = ["cdylib"]

[dependencies]
emacs = "0.15"
libloading = "0.6.2"
tree-sitter = "0.17.1"
once_cell = "1.2.0"
